// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsSqlite
{
    public static unsafe partial class NativeMethods
    {
#if (UNITY_IOS || UNITY_WEBGL) && !UNITY_EDITOR
        const string __DllName = "__Internal";
#elif UNITY_ANDROID && !UNITY_EDITOR
        const string __DllName = "sqliteX";
#else
        const string __DllName = "libsqlite3";
#endif
        



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_busy_handler_arg2_delegate(void* arg1, int arg2);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_commit_hook_arg2_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_create_collation16_xCompare_delegate(void* arg1, int arg2, void* arg3, int arg4, void* arg5);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_create_collation_v2_xCompare_delegate(void* arg1, int arg2, void* arg3, int arg4, void* arg5);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_create_collation_xCompare_delegate(void* arg1, int arg2, void* arg3, int arg4, void* arg5);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_exec_callback_delegate(void* arg1, int arg2, byte** arg3, byte** arg4);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_progress_handler_arg3_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_rtree_geometry_callback_xGeom_delegate(sqlite3_rtree_geometry* arg1, int arg2, double* arg3, int* arg4);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_rtree_query_callback_xQueryFunc_delegate(sqlite3_rtree_query_info* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_set_authorizer_xAuth_delegate(void* arg1, int arg2, byte* arg3, byte* arg4, byte* arg5, byte* arg6);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_trace_v2_xCallback_delegate(uint arg1, void* arg2, void* arg3, void* arg4);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int sqlite3_wal_hook_arg2_delegate(void* arg1, sqlite3* arg2, byte* arg3, int arg4);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate uint sqlite3_autovacuum_pages_arg1_delegate(void* arg1, byte* arg2, uint arg3, uint arg4, uint arg5);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_auto_extension_xEntryPoint_delegate();

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_autovacuum_pages_arg3_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_bind_blob64_arg5_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_bind_blob_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_bind_pointer_arg5_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_bind_text16_arg5_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_bind_text64_arg5_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_bind_text_arg5_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_cancel_auto_extension_xEntryPoint_delegate();

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_collation_needed16_arg3_delegate(void* arg1, sqlite3* arg2, int eTextRep, void* arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_collation_needed_arg3_delegate(void* arg1, sqlite3* arg2, int eTextRep, byte* arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_collation_v2_xDestroy_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function16_xFinal_delegate(sqlite3_context* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function16_xFunc_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function16_xStep_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_v2_xDestroy_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_v2_xFinal_delegate(sqlite3_context* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_v2_xFunc_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_v2_xStep_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_xFinal_delegate(sqlite3_context* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_xFunc_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_function_xStep_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_module_v2_xDestroy_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_window_function_xDestroy_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_window_function_xFinal_delegate(sqlite3_context* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_window_function_xInverse_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_window_function_xStep_delegate(sqlite3_context* arg1, int arg2, sqlite3_value** arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_create_window_function_xValue_delegate(sqlite3_context* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_memory_alarm_arg1_delegate(void* arg1, long arg2, int arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_profile_xProfile_delegate(void* arg1, byte* arg2, ulong arg3);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_blob64_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_blob_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_pointer_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_text16_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_text16be_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_text16le_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_text64_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_result_text_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_rollback_hook_arg2_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_rtree_query_callback_xDestructor_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_set_auxdata_arg3_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_set_clientdata_arg4_delegate(void* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_trace_xTrace_delegate(void* arg1, byte* arg2);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_unlock_notify_xNotify_delegate(void** apArg, int nArg);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void sqlite3_update_hook_arg2_delegate(void* arg1, int arg2, byte* arg3, byte* arg4, long arg5);



        [DllImport(__DllName, EntryPoint = "sqlite3_libversion", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_libversion();

        [DllImport(__DllName, EntryPoint = "sqlite3_sourceid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_sourceid();

        [DllImport(__DllName, EntryPoint = "sqlite3_libversion_number", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_libversion_number();

        [DllImport(__DllName, EntryPoint = "sqlite3_compileoption_used", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_compileoption_used(byte* zOptName);

        [DllImport(__DllName, EntryPoint = "sqlite3_compileoption_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_compileoption_get(int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_threadsafe", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_threadsafe();

        [DllImport(__DllName, EntryPoint = "sqlite3_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_close(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_close_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_close_v2(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_exec", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_exec(sqlite3* arg1, byte* sql, sqlite3_exec_callback_delegate callback, void* arg2, byte** errmsg);

        [DllImport(__DllName, EntryPoint = "sqlite3_initialize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_initialize();

        [DllImport(__DllName, EntryPoint = "sqlite3_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_shutdown();

        [DllImport(__DllName, EntryPoint = "sqlite3_os_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_os_init();

        [DllImport(__DllName, EntryPoint = "sqlite3_os_end", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_os_end();

        [DllImport(__DllName, EntryPoint = "sqlite3_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_config(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_db_config(sqlite3* arg1, int op);

        [DllImport(__DllName, EntryPoint = "sqlite3_extended_result_codes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_extended_result_codes(sqlite3* arg1, int onoff);

        [DllImport(__DllName, EntryPoint = "sqlite3_last_insert_rowid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_last_insert_rowid(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_set_last_insert_rowid", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_set_last_insert_rowid(sqlite3* arg1, long arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_changes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_changes(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_changes64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_changes64(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_total_changes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_total_changes(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_total_changes64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_total_changes64(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_interrupt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_interrupt(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_is_interrupted", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_is_interrupted(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_complete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_complete(byte* sql);

        [DllImport(__DllName, EntryPoint = "sqlite3_complete16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_complete16(void* sql);

        [DllImport(__DllName, EntryPoint = "sqlite3_busy_handler", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_busy_handler(sqlite3* arg1, sqlite3_busy_handler_arg2_delegate arg2, void* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_busy_timeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_busy_timeout(sqlite3* arg1, int ms);

        [DllImport(__DllName, EntryPoint = "sqlite3_setlk_timeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_setlk_timeout(sqlite3* arg1, int ms, int flags);

        [DllImport(__DllName, EntryPoint = "sqlite3_free_table", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_free_table(byte** result);

        [DllImport(__DllName, EntryPoint = "sqlite3_mprintf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_mprintf(byte* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_vmprintf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_vmprintf(byte* arg1, byte* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_snprintf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_snprintf(int arg1, byte* arg2, byte* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_vsnprintf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_vsnprintf(int arg1, byte* arg2, byte* arg3, byte* arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_malloc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_malloc(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_malloc64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_malloc64(ulong arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_realloc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_realloc(void* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_realloc64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_realloc64(void* arg1, ulong arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_free(void* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_msize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong sqlite3_msize(void* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_memory_used", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_memory_used();

        [DllImport(__DllName, EntryPoint = "sqlite3_memory_highwater", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_memory_highwater(int resetFlag);

        [DllImport(__DllName, EntryPoint = "sqlite3_randomness", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_randomness(int N, void* P);

        [DllImport(__DllName, EntryPoint = "sqlite3_set_authorizer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_set_authorizer(sqlite3* arg1, sqlite3_set_authorizer_xAuth_delegate xAuth, void* pUserData);

        [DllImport(__DllName, EntryPoint = "sqlite3_trace", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_trace(sqlite3* arg1, sqlite3_trace_xTrace_delegate xTrace, void* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_profile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_profile(sqlite3* arg1, sqlite3_profile_xProfile_delegate xProfile, void* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_trace_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_trace_v2(sqlite3* arg1, uint uMask, sqlite3_trace_v2_xCallback_delegate xCallback, void* pCtx);

        [DllImport(__DllName, EntryPoint = "sqlite3_progress_handler", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_progress_handler(sqlite3* arg1, int arg2, sqlite3_progress_handler_arg3_delegate arg3, void* arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_open(byte* filename, sqlite3** ppDb);

        [DllImport(__DllName, EntryPoint = "sqlite3_open16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_open16(void* filename, sqlite3** ppDb);

        [DllImport(__DllName, EntryPoint = "sqlite3_open_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_open_v2(byte* filename, sqlite3** ppDb, int flags, byte* zVfs);

        [DllImport(__DllName, EntryPoint = "sqlite3_uri_parameter", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_uri_parameter(byte* z, byte* zParam);

        [DllImport(__DllName, EntryPoint = "sqlite3_uri_boolean", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_uri_boolean(byte* z, byte* zParam, int bDefault);

        [DllImport(__DllName, EntryPoint = "sqlite3_uri_int64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_uri_int64(byte* arg1, byte* arg2, long arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_uri_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_uri_key(byte* z, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_filename_database", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_filename_database(byte* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_filename_journal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_filename_journal(byte* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_filename_wal", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_filename_wal(byte* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_database_file_object", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_file* sqlite3_database_file_object(byte* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_filename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_create_filename(byte* zDatabase, byte* zJournal, byte* zWal, int nParam, byte** azParam);

        [DllImport(__DllName, EntryPoint = "sqlite3_free_filename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_free_filename(byte* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_errcode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_errcode(sqlite3* db);

        [DllImport(__DllName, EntryPoint = "sqlite3_extended_errcode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_extended_errcode(sqlite3* db);

        [DllImport(__DllName, EntryPoint = "sqlite3_errmsg", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_errmsg(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_errmsg16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_errmsg16(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_errstr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_errstr(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_error_offset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_error_offset(sqlite3* db);

        [DllImport(__DllName, EntryPoint = "sqlite3_limit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_limit(sqlite3* arg1, int id, int newVal);

        [DllImport(__DllName, EntryPoint = "sqlite3_prepare", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_prepare(sqlite3* db, byte* zSql, int nByte, sqlite3_stmt** ppStmt, byte** pzTail);

        [DllImport(__DllName, EntryPoint = "sqlite3_prepare_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_prepare_v2(sqlite3* db, byte* zSql, int nByte, sqlite3_stmt** ppStmt, byte** pzTail);

        [DllImport(__DllName, EntryPoint = "sqlite3_prepare_v3", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_prepare_v3(sqlite3* db, byte* zSql, int nByte, uint prepFlags, sqlite3_stmt** ppStmt, byte** pzTail);

        [DllImport(__DllName, EntryPoint = "sqlite3_prepare16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_prepare16(sqlite3* db, void* zSql, int nByte, sqlite3_stmt** ppStmt, void** pzTail);

        [DllImport(__DllName, EntryPoint = "sqlite3_prepare16_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_prepare16_v2(sqlite3* db, void* zSql, int nByte, sqlite3_stmt** ppStmt, void** pzTail);

        [DllImport(__DllName, EntryPoint = "sqlite3_prepare16_v3", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_prepare16_v3(sqlite3* db, void* zSql, int nByte, uint prepFlags, sqlite3_stmt** ppStmt, void** pzTail);

        [DllImport(__DllName, EntryPoint = "sqlite3_sql", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_sql(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_expanded_sql", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_expanded_sql(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_readonly", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_readonly(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_isexplain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_isexplain(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_explain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_explain(sqlite3_stmt* pStmt, int eMode);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_busy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_busy(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_blob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_blob(sqlite3_stmt* arg1, int arg2, void* arg3, int n, sqlite3_bind_blob_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_blob64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_blob64(sqlite3_stmt* arg1, int arg2, void* arg3, ulong arg4, sqlite3_bind_blob64_arg5_delegate arg5);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_double(sqlite3_stmt* arg1, int arg2, double arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_int(sqlite3_stmt* arg1, int arg2, int arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_int64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_int64(sqlite3_stmt* arg1, int arg2, long arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_null", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_null(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_text(sqlite3_stmt* arg1, int arg2, byte* arg3, int arg4, sqlite3_bind_text_arg5_delegate arg5);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_text16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_text16(sqlite3_stmt* arg1, int arg2, void* arg3, int arg4, sqlite3_bind_text16_arg5_delegate arg5);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_text64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_text64(sqlite3_stmt* arg1, int arg2, byte* arg3, ulong arg4, sqlite3_bind_text64_arg5_delegate arg5, byte encoding);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_value(sqlite3_stmt* arg1, int arg2, sqlite3_value* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_pointer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_pointer(sqlite3_stmt* arg1, int arg2, void* arg3, byte* arg4, sqlite3_bind_pointer_arg5_delegate arg5);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_zeroblob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_zeroblob(sqlite3_stmt* arg1, int arg2, int n);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_zeroblob64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_zeroblob64(sqlite3_stmt* arg1, int arg2, ulong arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_parameter_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_parameter_count(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_parameter_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_bind_parameter_name(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_bind_parameter_index", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_bind_parameter_index(sqlite3_stmt* arg1, byte* zName);

        [DllImport(__DllName, EntryPoint = "sqlite3_clear_bindings", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_clear_bindings(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_column_count(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_column_name(sqlite3_stmt* arg1, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_name16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_name16(sqlite3_stmt* arg1, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_database_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_column_database_name(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_database_name16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_database_name16(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_table_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_column_table_name(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_table_name16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_table_name16(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_origin_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_column_origin_name(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_origin_name16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_origin_name16(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_decltype", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_column_decltype(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_decltype16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_decltype16(sqlite3_stmt* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_step", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_step(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_data_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_data_count(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_blob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_blob(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sqlite3_column_double(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_column_int(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_int64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_column_int64(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_column_text(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_text16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_column_text16(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_value* sqlite3_column_value(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_column_bytes(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_bytes16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_column_bytes16(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_column_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_column_type(sqlite3_stmt* arg1, int iCol);

        [DllImport(__DllName, EntryPoint = "sqlite3_finalize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_finalize(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_reset(sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_function", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_function(sqlite3* db, byte* zFunctionName, int nArg, int eTextRep, void* pApp, sqlite3_create_function_xFunc_delegate xFunc, sqlite3_create_function_xStep_delegate xStep, sqlite3_create_function_xFinal_delegate xFinal);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_function16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_function16(sqlite3* db, void* zFunctionName, int nArg, int eTextRep, void* pApp, sqlite3_create_function16_xFunc_delegate xFunc, sqlite3_create_function16_xStep_delegate xStep, sqlite3_create_function16_xFinal_delegate xFinal);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_function_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_function_v2(sqlite3* db, byte* zFunctionName, int nArg, int eTextRep, void* pApp, sqlite3_create_function_v2_xFunc_delegate xFunc, sqlite3_create_function_v2_xStep_delegate xStep, sqlite3_create_function_v2_xFinal_delegate xFinal, sqlite3_create_function_v2_xDestroy_delegate xDestroy);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_window_function", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_window_function(sqlite3* db, byte* zFunctionName, int nArg, int eTextRep, void* pApp, sqlite3_create_window_function_xStep_delegate xStep, sqlite3_create_window_function_xFinal_delegate xFinal, sqlite3_create_window_function_xValue_delegate xValue, sqlite3_create_window_function_xInverse_delegate xInverse, sqlite3_create_window_function_xDestroy_delegate xDestroy);

        [DllImport(__DllName, EntryPoint = "sqlite3_aggregate_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_aggregate_count(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_expired", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_expired(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_transfer_bindings", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_transfer_bindings(sqlite3_stmt* arg1, sqlite3_stmt* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_global_recover", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_global_recover();

        [DllImport(__DllName, EntryPoint = "sqlite3_thread_cleanup", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_thread_cleanup();

        [DllImport(__DllName, EntryPoint = "sqlite3_memory_alarm", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_memory_alarm(sqlite3_memory_alarm_arg1_delegate arg1, void* arg2, long arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_blob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_value_blob(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double sqlite3_value_double(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_int(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_int64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_value_int64(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_pointer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_value_pointer(sqlite3_value* arg1, byte* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_value_text(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_text16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_value_text16(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_text16le", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_value_text16le(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_text16be", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_value_text16be(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_bytes(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_bytes16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_bytes16(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_type(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_numeric_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_numeric_type(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_nochange", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_nochange(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_frombind", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_frombind(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_encoding", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_value_encoding(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_subtype", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint sqlite3_value_subtype(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_dup", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_value* sqlite3_value_dup(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_value_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_value_free(sqlite3_value* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_aggregate_context", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_aggregate_context(sqlite3_context* arg1, int nBytes);

        [DllImport(__DllName, EntryPoint = "sqlite3_user_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_user_data(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_context_db_handle", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3* sqlite3_context_db_handle(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_get_auxdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_get_auxdata(sqlite3_context* arg1, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_set_auxdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_set_auxdata(sqlite3_context* arg1, int N, void* arg2, sqlite3_set_auxdata_arg3_delegate arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_get_clientdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_get_clientdata(sqlite3* arg1, byte* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_set_clientdata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_set_clientdata(sqlite3* arg1, byte* arg2, void* arg3, sqlite3_set_clientdata_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_blob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_blob(sqlite3_context* arg1, void* arg2, int arg3, sqlite3_result_blob_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_blob64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_blob64(sqlite3_context* arg1, void* arg2, ulong arg3, sqlite3_result_blob64_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_double", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_double(sqlite3_context* arg1, double arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_error(sqlite3_context* arg1, byte* arg2, int arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_error16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_error16(sqlite3_context* arg1, void* arg2, int arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_error_toobig", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_error_toobig(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_error_nomem", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_error_nomem(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_error_code", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_error_code(sqlite3_context* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_int", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_int(sqlite3_context* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_int64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_int64(sqlite3_context* arg1, long arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_null", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_null(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_text(sqlite3_context* arg1, byte* arg2, int arg3, sqlite3_result_text_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_text64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_text64(sqlite3_context* arg1, byte* arg2, ulong arg3, sqlite3_result_text64_arg4_delegate arg4, byte encoding);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_text16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_text16(sqlite3_context* arg1, void* arg2, int arg3, sqlite3_result_text16_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_text16le", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_text16le(sqlite3_context* arg1, void* arg2, int arg3, sqlite3_result_text16le_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_text16be", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_text16be(sqlite3_context* arg1, void* arg2, int arg3, sqlite3_result_text16be_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_value(sqlite3_context* arg1, sqlite3_value* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_pointer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_pointer(sqlite3_context* arg1, void* arg2, byte* arg3, sqlite3_result_pointer_arg4_delegate arg4);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_zeroblob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_zeroblob(sqlite3_context* arg1, int n);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_zeroblob64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_result_zeroblob64(sqlite3_context* arg1, ulong n);

        [DllImport(__DllName, EntryPoint = "sqlite3_result_subtype", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_result_subtype(sqlite3_context* arg1, uint arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_collation", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_collation(sqlite3* arg1, byte* zName, int eTextRep, void* pArg, sqlite3_create_collation_xCompare_delegate xCompare);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_collation_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_collation_v2(sqlite3* arg1, byte* zName, int eTextRep, void* pArg, sqlite3_create_collation_v2_xCompare_delegate xCompare, sqlite3_create_collation_v2_xDestroy_delegate xDestroy);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_collation16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_collation16(sqlite3* arg1, void* zName, int eTextRep, void* pArg, sqlite3_create_collation16_xCompare_delegate xCompare);

        [DllImport(__DllName, EntryPoint = "sqlite3_collation_needed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_collation_needed(sqlite3* arg1, void* arg2, sqlite3_collation_needed_arg3_delegate arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_collation_needed16", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_collation_needed16(sqlite3* arg1, void* arg2, sqlite3_collation_needed16_arg3_delegate arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_sleep", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_sleep(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_get_autocommit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_get_autocommit(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_handle", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3* sqlite3_db_handle(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_db_name(sqlite3* db, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_filename", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_db_filename(sqlite3* db, byte* zDbName);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_readonly", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_db_readonly(sqlite3* db, byte* zDbName);

        [DllImport(__DllName, EntryPoint = "sqlite3_txn_state", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_txn_state(sqlite3* arg1, byte* zSchema);

        [DllImport(__DllName, EntryPoint = "sqlite3_next_stmt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_stmt* sqlite3_next_stmt(sqlite3* pDb, sqlite3_stmt* pStmt);

        [DllImport(__DllName, EntryPoint = "sqlite3_commit_hook", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_commit_hook(sqlite3* arg1, sqlite3_commit_hook_arg2_delegate arg2, void* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_rollback_hook", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_rollback_hook(sqlite3* arg1, sqlite3_rollback_hook_arg2_delegate arg2, void* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_autovacuum_pages", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_autovacuum_pages(sqlite3* db, sqlite3_autovacuum_pages_arg1_delegate arg1, void* arg2, sqlite3_autovacuum_pages_arg3_delegate arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_update_hook", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_update_hook(sqlite3* arg1, sqlite3_update_hook_arg2_delegate arg2, void* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_enable_shared_cache", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_enable_shared_cache(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_release_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_release_memory(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_release_memory", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_db_release_memory(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_soft_heap_limit64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_soft_heap_limit64(long N);

        [DllImport(__DllName, EntryPoint = "sqlite3_hard_heap_limit64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern long sqlite3_hard_heap_limit64(long N);

        [DllImport(__DllName, EntryPoint = "sqlite3_soft_heap_limit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_soft_heap_limit(int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_table_column_metadata", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_table_column_metadata(sqlite3* db, byte* zDbName, byte* zTableName, byte* zColumnName, byte** pzDataType, byte** pzCollSeq, int* pNotNull, int* pPrimaryKey, int* pAutoinc);

        [DllImport(__DllName, EntryPoint = "sqlite3_load_extension", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_load_extension(sqlite3* db, byte* zFile, byte* zProc, byte** pzErrMsg);

        [DllImport(__DllName, EntryPoint = "sqlite3_enable_load_extension", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_enable_load_extension(sqlite3* db, int onoff);

        [DllImport(__DllName, EntryPoint = "sqlite3_auto_extension", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_auto_extension(sqlite3_auto_extension_xEntryPoint_delegate xEntryPoint);

        [DllImport(__DllName, EntryPoint = "sqlite3_cancel_auto_extension", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_cancel_auto_extension(sqlite3_cancel_auto_extension_xEntryPoint_delegate xEntryPoint);

        [DllImport(__DllName, EntryPoint = "sqlite3_reset_auto_extension", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_reset_auto_extension();

        [DllImport(__DllName, EntryPoint = "sqlite3_create_module", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_module(sqlite3* db, byte* zName, sqlite3_module* p, void* pClientData);

        [DllImport(__DllName, EntryPoint = "sqlite3_create_module_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_create_module_v2(sqlite3* db, byte* zName, sqlite3_module* p, void* pClientData, sqlite3_create_module_v2_xDestroy_delegate xDestroy);

        [DllImport(__DllName, EntryPoint = "sqlite3_drop_modules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_drop_modules(sqlite3* db, byte** azKeep);

        [DllImport(__DllName, EntryPoint = "sqlite3_declare_vtab", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_declare_vtab(sqlite3* arg1, byte* zSQL);

        [DllImport(__DllName, EntryPoint = "sqlite3_overload_function", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_overload_function(sqlite3* arg1, byte* zFuncName, int nArg);

        [DllImport(__DllName, EntryPoint = "sqlite3_blob_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_blob_open(sqlite3* arg1, byte* zDb, byte* zTable, byte* zColumn, long iRow, int flags, sqlite3_blob** ppBlob);

        [DllImport(__DllName, EntryPoint = "sqlite3_blob_reopen", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_blob_reopen(sqlite3_blob* arg1, long arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_blob_close", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_blob_close(sqlite3_blob* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_blob_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_blob_bytes(sqlite3_blob* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_blob_read", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_blob_read(sqlite3_blob* arg1, void* Z, int N, int iOffset);

        [DllImport(__DllName, EntryPoint = "sqlite3_blob_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_blob_write(sqlite3_blob* arg1, void* z, int n, int iOffset);

        [DllImport(__DllName, EntryPoint = "sqlite3_vfs_find", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_vfs* sqlite3_vfs_find(byte* zVfsName);

        [DllImport(__DllName, EntryPoint = "sqlite3_vfs_register", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vfs_register(sqlite3_vfs* arg1, int makeDflt);

        [DllImport(__DllName, EntryPoint = "sqlite3_vfs_unregister", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vfs_unregister(sqlite3_vfs* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_alloc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_mutex* sqlite3_mutex_alloc(int arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_mutex_free(sqlite3_mutex* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_enter", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_mutex_enter(sqlite3_mutex* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_try", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_mutex_try(sqlite3_mutex* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_leave", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_mutex_leave(sqlite3_mutex* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_held", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_mutex_held(sqlite3_mutex* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_mutex_notheld", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_mutex_notheld(sqlite3_mutex* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_mutex", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_mutex* sqlite3_db_mutex(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_file_control", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_file_control(sqlite3* arg1, byte* zDbName, int op, void* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_test_control", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_test_control(int op);

        [DllImport(__DllName, EntryPoint = "sqlite3_keyword_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_keyword_count();

        [DllImport(__DllName, EntryPoint = "sqlite3_keyword_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_keyword_name(int arg1, byte** arg2, int* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_keyword_check", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_keyword_check(byte* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_str* sqlite3_str_new(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_finish", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_str_finish(sqlite3_str* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_appendf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_str_appendf(sqlite3_str* arg1, byte* zFormat);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_vappendf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_str_vappendf(sqlite3_str* arg1, byte* zFormat, byte* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_append", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_str_append(sqlite3_str* arg1, byte* zIn, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_appendall", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_str_appendall(sqlite3_str* arg1, byte* zIn);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_appendchar", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_str_appendchar(sqlite3_str* arg1, int N, byte C);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_str_reset(sqlite3_str* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_errcode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_str_errcode(sqlite3_str* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_length", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_str_length(sqlite3_str* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_str_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_str_value(sqlite3_str* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_status(int op, int* pCurrent, int* pHighwater, int resetFlag);

        [DllImport(__DllName, EntryPoint = "sqlite3_status64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_status64(int op, long* pCurrent, long* pHighwater, int resetFlag);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_db_status(sqlite3* arg1, int op, int* pCur, int* pHiwtr, int resetFlg);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_status", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_status(sqlite3_stmt* arg1, int op, int resetFlg);

        [DllImport(__DllName, EntryPoint = "sqlite3_backup_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern sqlite3_backup* sqlite3_backup_init(sqlite3* pDest, byte* zDestName, sqlite3* pSource, byte* zSourceName);

        [DllImport(__DllName, EntryPoint = "sqlite3_backup_step", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_backup_step(sqlite3_backup* p, int nPage);

        [DllImport(__DllName, EntryPoint = "sqlite3_backup_finish", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_backup_finish(sqlite3_backup* p);

        [DllImport(__DllName, EntryPoint = "sqlite3_backup_remaining", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_backup_remaining(sqlite3_backup* p);

        [DllImport(__DllName, EntryPoint = "sqlite3_backup_pagecount", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_backup_pagecount(sqlite3_backup* p);

        [DllImport(__DllName, EntryPoint = "sqlite3_unlock_notify", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_unlock_notify(sqlite3* pBlocked, sqlite3_unlock_notify_xNotify_delegate xNotify, void* pNotifyArg);

        [DllImport(__DllName, EntryPoint = "sqlite3_stricmp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stricmp(byte* arg1, byte* arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_strnicmp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_strnicmp(byte* arg1, byte* arg2, int arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_strglob", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_strglob(byte* zGlob, byte* zStr);

        [DllImport(__DllName, EntryPoint = "sqlite3_strlike", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_strlike(byte* zGlob, byte* zStr, uint cEsc);

        [DllImport(__DllName, EntryPoint = "sqlite3_log", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_log(int iErrCode, byte* zFormat);

        [DllImport(__DllName, EntryPoint = "sqlite3_wal_hook", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* sqlite3_wal_hook(sqlite3* arg1, sqlite3_wal_hook_arg2_delegate arg2, void* arg3);

        [DllImport(__DllName, EntryPoint = "sqlite3_wal_autocheckpoint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_wal_autocheckpoint(sqlite3* db, int N);

        [DllImport(__DllName, EntryPoint = "sqlite3_wal_checkpoint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_wal_checkpoint(sqlite3* db, byte* zDb);

        [DllImport(__DllName, EntryPoint = "sqlite3_wal_checkpoint_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_wal_checkpoint_v2(sqlite3* db, byte* zDb, int eMode, int* pnLog, int* pnCkpt);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_config(sqlite3* arg1, int op);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_on_conflict", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_on_conflict(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_nochange", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_nochange(sqlite3_context* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_collation", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_vtab_collation(sqlite3_index_info* arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_distinct", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_distinct(sqlite3_index_info* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_in", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_in(sqlite3_index_info* arg1, int iCons, int bHandle);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_in_first", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_in_first(sqlite3_value* pVal, sqlite3_value** ppOut);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_in_next", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_in_next(sqlite3_value* pVal, sqlite3_value** ppOut);

        [DllImport(__DllName, EntryPoint = "sqlite3_vtab_rhs_value", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_vtab_rhs_value(sqlite3_index_info* arg1, int arg2, sqlite3_value** ppVal);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_scanstatus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_scanstatus(sqlite3_stmt* pStmt, int idx, int iScanStatusOp, void* pOut);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_scanstatus_v2", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_stmt_scanstatus_v2(sqlite3_stmt* pStmt, int idx, int iScanStatusOp, int flags, void* pOut);

        [DllImport(__DllName, EntryPoint = "sqlite3_stmt_scanstatus_reset", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_stmt_scanstatus_reset(sqlite3_stmt* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_db_cacheflush", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_db_cacheflush(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_system_errno", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_system_errno(sqlite3* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_snapshot_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_snapshot_get(sqlite3* db, byte* zSchema, sqlite3_snapshot** ppSnapshot);

        [DllImport(__DllName, EntryPoint = "sqlite3_snapshot_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_snapshot_open(sqlite3* db, byte* zSchema, sqlite3_snapshot* pSnapshot);

        [DllImport(__DllName, EntryPoint = "sqlite3_snapshot_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void sqlite3_snapshot_free(sqlite3_snapshot* arg1);

        [DllImport(__DllName, EntryPoint = "sqlite3_snapshot_cmp", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_snapshot_cmp(sqlite3_snapshot* p1, sqlite3_snapshot* p2);

        [DllImport(__DllName, EntryPoint = "sqlite3_snapshot_recover", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_snapshot_recover(sqlite3* db, byte* zDb);

        [DllImport(__DllName, EntryPoint = "sqlite3_serialize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* sqlite3_serialize(sqlite3* db, byte* zSchema, long* piSize, uint mFlags);

        [DllImport(__DllName, EntryPoint = "sqlite3_deserialize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_deserialize(sqlite3* db, byte* zSchema, byte* pData, long szDb, long szBuf, uint mFlags);

        [DllImport(__DllName, EntryPoint = "sqlite3_rtree_geometry_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_rtree_geometry_callback(sqlite3* db, byte* zGeom, sqlite3_rtree_geometry_callback_xGeom_delegate xGeom, void* pContext);

        [DllImport(__DllName, EntryPoint = "sqlite3_rtree_query_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int sqlite3_rtree_query_callback(sqlite3* db, byte* zQueryFunc, sqlite3_rtree_query_callback_xQueryFunc_delegate xQueryFunc, void* pContext, sqlite3_rtree_query_callback_xDestructor_delegate xDestructor);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_file
    {
        public sqlite3_io_methods* pMethods;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_io_methods
    {
        public int iVersion;
        public void* xClose;
        public void* xRead;
        public void* xWrite;
        public void* xTruncate;
        public void* xSync;
        public void* xFileSize;
        public void* xLock;
        public void* xUnlock;
        public void* xCheckReservedLock;
        public void* xFileControl;
        public void* xSectorSize;
        public void* xDeviceCharacteristics;
        public void* xShmMap;
        public void* xShmLock;
        public void* xShmBarrier;
        public void* xShmUnmap;
        public void* xFetch;
        public void* xUnfetch;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_mutex
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_vfs
    {
        public int iVersion;
        public int szOsFile;
        public int mxPathname;
        public sqlite3_vfs* pNext;
        public byte* zName;
        public void* pAppData;
        public void* xOpen;
        public void* xDelete;
        public void* xAccess;
        public void* xFullPathname;
        public void* xDlOpen;
        public void* xDlError;
        public void* xDlSym;
        public void* xDlClose;
        public void* xRandomness;
        public void* xSleep;
        public void* xCurrentTime;
        public void* xGetLastError;
        public void* xCurrentTimeInt64;
        public void* xSetSystemCall;
        public void* xGetSystemCall;
        public void* xNextSystemCall;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_stmt
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_value
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_context
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_module
    {
        public int iVersion;
        public void* xCreate;
        public void* xConnect;
        public void* xBestIndex;
        public void* xDisconnect;
        public void* xDestroy;
        public void* xOpen;
        public void* xClose;
        public void* xFilter;
        public void* xNext;
        public void* xEof;
        public void* xColumn;
        public void* xRowid;
        public void* xUpdate;
        public void* xBegin;
        public void* xSync;
        public void* xCommit;
        public void* xRollback;
        public void* xFindFunction;
        public void* xRename;
        public void* xSavepoint;
        public void* xRelease;
        public void* xRollbackTo;
        public void* xShadowName;
        public void* xIntegrity;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_index_info
    {
        public int nConstraint;
        public sqlite3_index_info_sqlite3_index_constraint* aConstraint;
        public int nOrderBy;
        public sqlite3_index_info_sqlite3_index_orderby* aOrderBy;
        public sqlite3_index_info_sqlite3_index_constraint_usage* aConstraintUsage;
        public int idxNum;
        public byte* idxStr;
        public int needToFreeIdxStr;
        public int orderByConsumed;
        public double estimatedCost;
        public long estimatedRows;
        public int idxFlags;
        public ulong colUsed;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_index_info_sqlite3_index_constraint
    {
        public int iColumn;
        public byte op;
        public byte usable;
        public int iTermOffset;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_index_info_sqlite3_index_orderby
    {
        public int iColumn;
        public byte desc;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_index_info_sqlite3_index_constraint_usage
    {
        public int argvIndex;
        public byte omit;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_vtab
    {
        public sqlite3_module* pModule;
        public int nRef;
        public byte* zErrMsg;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_vtab_cursor
    {
        public sqlite3_vtab* pVtab;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_blob
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_str
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_backup
    {
        public fixed byte _unused[1];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_snapshot
    {
        public fixed byte hidden[48];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_rtree_geometry
    {
        public void* pContext;
        public int nParam;
        public double* aParam;
        public void* pUser;
        public void* xDelUser;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct sqlite3_rtree_query_info
    {
        public void* pContext;
        public int nParam;
        public double* aParam;
        public void* pUser;
        public void* xDelUser;
        public double* aCoord;
        public uint* anQueue;
        public int nCoord;
        public int iLevel;
        public int mxLevel;
        public long iRowid;
        public double rParentScore;
        public int eParentWithin;
        public int eWithin;
        public double rScore;
        public sqlite3_value** apSqlParam;
    }



}
