[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
csbindgen = { path = "/Users/yusuke/Desktop/Projects/Clones/csbindgen/csbindgen" }